# Base configs
<<<<<<< HEAD
baseurl: ""
=======
baseurl: "http://yoann-audrey.tk"
>>>>>>> 2f10909cb49948425a6ca32dd1e7603c5e297a00
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Mariage de Yoann & Audrey 18 Mai 2019"
subtitle: ""
author: "Andry RAJOHNSON"
header:
 title: "all photos are Take by"
 subtitle: "Andry RAJOHNSON"
footer: 
 name: ""
 bio: ""
 github: ""
web_design: " by Andry RAJOHNSON, Fullstack Developer, made with Jekyll and hosted on Github Pages"
social_urls:
  twitter: "https://www.twitter.com/rajohnsonandry"
  github: "https://www.github.com/andryjohn"
