# Base configs
baseurl: ""
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Mariage de Audrey & Yoann 18 Mai 2019"
subtitle: "Le weekend du 18 Mai 2019, Audrey & Yoann ont célèbré leur mariage, je vous partage ici, une librairie 
 de photos de cet évènement "
author: "Andry RAJOHNSON"
header:
 title: "astuce:"
 subtitle: "mettre plein écran"
footer: 
 name: "Merci pour votre visite!"
 bio: "Si vous souhaitez voir d'autres projets, c'est <a href=\"https://github.com/andryjohn\">ici!</a>"
 github: ""
web_design: "Andry RAJOHNSON Fullstack Developer, made with Jekyll and hosted on Github Pages"
social_urls:
  twitter: "https://www.twitter.com/rajohnsonandry"
  github: "https://www.github.com/andryjohn"
