# Base configs
baseurl: ""
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: ""
subtitle: ""
author: ""
header:
 title: "Photography"
 subtitle: "by "
footer:
 name: ""
 bio: ""
 github: ""
web_design: ""
social_urls:
  facebook: "https://www.facebook.com/"
  twitter: "https://www.twitter.com/"
  instagram: "https://www.instagram.com/"
  dribbble: "https://dribbble.com/"
  linkedin: ""
  github: "https://www.github.com/"
