# Base configs
baseurl: ""
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Mariage de Audrey & Yoann 18 Mai 2019"
subtitle: ""
author: "Andry RAJOHNSON"
header:
 title: "astuce:"
 subtitle: "plein écran(F11)"
footer: 
 name: ""
 bio: ""
 github: ""
web_design: "Andry RAJOHNSON Fullstack Developer, made with Jekyll and hosted on Github Pages"
social_urls:
  twitter: "https://www.twitter.com/rajohnsonandry"
  github: "https://www.github.com/andryjohn"
